import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_Thai } from 'next/font/google'
import XProvider from '@/components/provider';
import fetchWithToken from '@/utils/fetchUtils';
import { cookies } from 'next/headers';
import { Toaster, toast } from 'react-hot-toast';
import { ConfigProvider } from 'antd';
const inter = Noto_Sans_Thai({
  style: ['normal'],
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'ITFindJOB',
  description: 'Generated by create nexst app',
}


async function isLoggedIn() {
  try {

    const cookieStore = cookies()
    const token = cookieStore.get("your_token_key_here") ? cookieStore.get("your_token_key_here")?.value : ""
    
    const response = await fetchWithToken("/auth/me", { method: "GET", headers: { Authorization: `Bearer ${token}` } }, 60)
    if (await response.ok) {
      return await response.json();
    } else {
      return {}
    }
  }
  catch {
    return {}
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const test = await isLoggedIn();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider theme={{
          token: {
            colorPrimary: "#059669",
            colorLinkHover: "rgb(107 114 128)",
            colorLinkActive: "#ddd",
          },
        }}>
          <XProvider initialData={{ test }}>
            <Toaster position="bottom-center" />
            {children}
          </XProvider>
        </ConfigProvider>

      </body>
    </html>
  )
}
