version: '3'
services:
  web-backend:
    image: fewfewfewfewfew/backend:latest
    pull_policy: always
    build: backend
    ports:
      - "5000:5000"

  web-frontend:
    image: fewfewfewfewfew/frontend:latest
    pull_policy: always
    build: frontend
    ports:
      - "3000:3000"

  web:
    image: nginx
    ports:
      - "8080:80"
