version: '3'
services:
  web-backend:
    image: fewfindjob-web-backend
    build: /backend
    ports:
      - "5000:5000"

  web-frontend:
    image: fewfindjob-web-frontend
    build: /frontend
    ports:
      - "3000:3000"